### ISSUE TITLE
exporting to a (non-existant) virtual environment

### ISSUE THREAD

**Issue by drjwan** [streeter/reserve-america-scraper#2]
I am a complete beginner, but have gotten this working right up to the point where I need to export my virtual environment. I installed the packages system-wide (because I am not a software developer), can the cron.sh code be modified to remove the need for a virtual environment? Any suggestions on lines to remove or modify? Something like the below? I am so close to waking up in glorious Yosemite Valley.

#!/bin/bash

PATH="/usr/local/bin:${PATH}"
BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

TERMINAL_NOTIFIER=`which terminal-notifier`
NOTIF_ARGS="-sender com.google.Chrome -open $CAMPGROUND"

sites=`source $BASE_DIR/scraper.py`

**Comment by streeter** [comment]
@drjwan, I went ahead and fixed the script to allow it to be run from outside of a virtualenv, with commit ea7cca9067e914503299f6d138bf66d246807447.

Hope that works for you!
